CREATE USER LOGIN_ONLY IDENTIFIED BY pass;
GRANT CREATE SESSION TO LOGIN_ONLY;
GRANT EXECUTE ON BDT.CHECK_LOGIN TO LOGIN_ONLY;

CREATE USER STUDENT IDENTIFIED BY pass;
GRANT CREATE SESSION TO STUDENT;
GRANT SELECT ON BD.FACULTY TO STUDENT;
GRANT SELECT ON BD."GROUP" TO STUDENT;
GRANT SELECT ON BD.PERSONAL_DATA TO STUDENT;
GRANT SELECT ON BD.PROFESSOR TO STUDENT;
GRANT SELECT ON BD."RECORD" TO STUDENT;
GRANT SELECT ON BD.SPECIALIZATION TO STUDENT;
GRANT SELECT ON BD.STUDENT TO STUDENT;
GRANT SELECT ON BD.SUBJECT TO STUDENT;

CREATE USER PROFESSOR IDENTIFIED BY pass;
GRANT CREATE SESSION TO PROFESSOR;
GRANT SELECT ON BD.FACULTY TO PROFESSOR;
GRANT SELECT ON BD.PROFESSOR TO PROFESSOR;
GRANT SELECT ON BD.SPECIALIZATION TO PROFESSOR;
GRANT SELECT ON BD."GROUP" TO PROFESSOR;
GRANT SELECT ON BD.PERSONAL_DATA TO PROFESSOR;
GRANT SELECT ON BD."RECORD" TO PROFESSOR;
GRANT SELECT ON BD.STUDENT TO PROFESSOR;
GRANT SELECT ON BD.SUBJECT TO PROFESSOR;
GRANT EXECUTE ON BD.ADD_GRADE TO PROFESSOR;
GRANT EXECUTE ON BD.REMOVE_GRADE TO PROFESSOR;


CREATE USER DEANS_WORKER IDENTIFIED BY pass;
GRANT CREATE SESSION TO DEANS_WORKER;
GRANT SELECT ON BD.DEANS_WORKER TO DEANS_WORKER;
GRANT SELECT ON BD.FACULTY TO DEANS_WORKER;
GRANT SELECT ON BD.PROFESSOR TO DEANS_WORKER;
GRANT SELECT ON BD.SPECIALIZATION TO DEANS_WORKER;
GRANT SELECT, INSERT, UPDATE, REMOVE ON BD."GROUP" TO DEANS_WORKER;
GRANT SELECT, INSERT, UPDATE, REMOVE ON BD.PERSONAL_DATA TO DEANS_WORKER;
GRANT SELECT, INSERT, UPDATE, REMOVE ON BD."RECORD" TO DEANS_WORKER;
GRANT SELECT, INSERT, UPDATE, REMOVE ON BD.STUDENT TO DEANS_WORKER;
GRANT SELECT, INSERT, UPDATE, REMOVE ON BD.SUBJECT TO DEANS_WORKER;
GRANT EXECUTE ON BD.ADD_STUDENT_TO_GROUP TO DEANS_WORKER;
GRANT EXECUTE ON BD.REMOVE_STUDENT_FROM_GROUP TO DEANS_WORKER;
