DROP USER "LOGIN_ONLY" CASCADE;
DROP USER "STUDENT" CASCADE;
DROP USER "PROFESSOR" CASCADE;
DROP USER "DEANS_WORKER" CASCADE;

alter session set "_ORACLE_SCRIPT"=true;
CREATE USER LOGIN_ONLY IDENTIFIED BY pass;
GRANT CREATE SESSION TO LOGIN_ONLY;
GRANT EXECUTE ON BD.CHECK_LOGIN TO LOGIN_ONLY;
GRANT EXECUTE ON BD.GET_ID TO LOGIN_ONLY;

alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER STUDENT IDENTIFIED BY pass;
GRANT CREATE SESSION TO STUDENT;
GRANT SELECT ON BD.STUDENT_VIEW TO STUDENT;
GRANT SELECT ON BD.STUDENT_GRADES_VIEW TO STUDENT;
GRANT SELECT ON BD.RECORD_VIEW TO STUDENT;

alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER PROFESSOR IDENTIFIED BY pass;
GRANT CREATE SESSION TO PROFESSOR;
GRANT SELECT ON BD.PROFESSOR_VIEW TO PROFESSOR;
GRANT SELECT ON BD.GROUP_VIEW TO PROFESSOR;
GRANT SELECT ON BD.GROUP_STUDENTS_VIEW TO PROFESSOR;
GRANT EXECUTE ON BD.ADD_GRADE TO PROFESSOR;
GRANT EXECUTE ON BD.REMOVE_GRADE TO PROFESSOR;

alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER DEANS_WORKER IDENTIFIED BY pass;
GRANT CREATE SESSION TO DEANS_WORKER;
GRANT SELECT ON BD.DEANS_WORKER_VIEW TO DEANS_WORKER;
GRANT SELECT ON BD.PROFESSOR_VIEW TO DEANS_WORKER;
GRANT SELECT ON BD.GROUP_VIEW TO DEANS_WORKER;
GRANT SELECT ON BD.GROUP_STUDENTS_VIEW TO DEANS_WORKER;
GRANT SELECT ON BD.SUBJECT TO DEANS_WORKER;
GRANT EXECUTE ON BD.ADD_GROUP TO DEANS_WORKER;
GRANT EXECUTE ON BD.ADD_STUDENT TO DEANS_WORKER;
GRANT EXECUTE ON BD.ADD_STUDENT_TO_GROUP TO DEANS_WORKER;
GRANT EXECUTE ON BD.REMOVE_GROUP TO DEANS_WORKER;
GRANT EXECUTE ON BD.REMOVE_STUDENT TO DEANS_WORKER;
GRANT EXECUTE ON BD.REMOVE_STUDENT_FROM_GROUP TO DEANS_WORKER;