--------------------------------------------------------
--  DDL for View GROUP_VIEW
--------------------------------------------------------

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "BD"."GROUP_VIEW" ("PROFESSOR_ID", "DEGREE", "FIRST_NAME", "LAST_NAME", "SUBJECT_ID", "SUBJECT_NAME", "PARITY", "TIME", "FORM", "DAY", "STUDENT_LIMIT") AS
SELECT
    PROFESSOR.PROFESSOR_ID,
    PROFESSOR.DEGREE,
    PERSONAL_DATA.FIRST_NAME,
    PERSONAL_DATA.LAST_NAME,
    "GROUP".SUBJECT_ID,
    SUBJECT.SUBJECT_NAME,
    "GROUP".PARITY,
    "GROUP".TIME,
    "GROUP".FORM,
    "GROUP".DAY,
    "GROUP".STUDENT_LIMIT
FROM
    "GROUP" INNER JOIN
    PROFESSOR ON "GROUP".PROFESSOR_ID = PROFESSOR.PROFESSOR_ID INNER JOIN
    PERSONAL_DATA ON PROFESSOR.PROFESSOR_ID = PERSONAL_DATA.USER_ID INNER JOIN
    SUBJECT ON SUBJECT.SUBJECT_ID = "GROUP".SUBJECT_ID;
--------------------------------------------------------
--  DDL for View GROUP_STUDENTS_VIEW
--------------------------------------------------------

CREATE OR REPLACE NONEDITIONABLE VIEW "GROUP_STUDENTS_VIEW" ("PROFESSOR_ID", "GROUP_ID", "STUDENT_ID", "STUDENT", "EMAIL", "GRADE", "GRADE_DATE", "RECORD_DATE") AS
SELECT
    grp.professor_id,
    grp."GROUP_ID",
    rec.student_id,
    pd.first_name || ' ' || pd.last_name as "STUDENT",
    pd.email,
    rec.grade,
    rec.grade_date,
    rec.record_date
FROM
    "GROUP" grp inner join
    "RECORD" rec on grp."GROUP_ID" = rec."GROUP_ID" inner join
    PERSONAL_DATA pd on rec.student_id = pd.user_id;
--------------------------------------------------------
--  DDL for View PROFESSOR_VIEW
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE VIEW "PROFESSOR_VIEW" ("PROFESSOR_ID", "DEGREE", "FIRST_NAME", "LAST_NAME", "EMAIL", "NAME") AS SELECT
	PROFESSOR.PROFESSOR_ID,
	PROFESSOR.DEGREE,
	PERSONAL_DATA.FIRST_NAME,
	PERSONAL_DATA.LAST_NAME,
	PERSONAL_DATA.EMAIL,
	FACULTY.NAME
FROM
	PROFESSOR INNER JOIN
	PERSONAL_DATA ON PROFESSOR.PROFESSOR_ID = PERSONAL_DATA.USER_ID INNER JOIN
    FACULTY ON faculty.faculity_id = personal_data.faculty_id;
--------------------------------------------------------
--  DDL for View STUDENT_VIEW
--------------------------------------------------------

CREATE OR REPLACE NONEDITIONABLE VIEW "STUDENT_VIEW" ("AVG_GRADE", "STUDENT_ID", "PESEL", "ADMISSION_DATE", "YEAR", "SEMESTER", "FIRST_NAME", "LAST_NAME", "EMAIL", "SPECIALIZATION", "FACULTY") AS
SELECT
    AVG("RECORD".GRADE) as AVG_GRADE,
    STUDENT.STUDENT_ID,
    STUDENT.PESEL,
    STUDENT.ADMISSION_DATE,
    STUDENT.YEAR,
    STUDENT.SEMESTER,
    PERSONAL_DATA.FIRST_NAME,
    PERSONAL_DATA.LAST_NAME,
    PERSONAL_DATA.EMAIL,
    SPECIALIZATION.NAME AS SPECIALIZATION,
    FACULTY.NAME AS FACULTY
FROM
    STUDENT INNER JOIN
    "RECORD" ON STUDENT.STUDENT_ID = "RECORD".STUDENT_ID INNER JOIN
    PERSONAL_DATA ON STUDENT.STUDENT_ID = PERSONAL_DATA.USER_ID INNER JOIN
    SPECIALIZATION ON STUDENT.SPECIALIZATION_ID = SPECIALIZATION.SPECIALIZATION_ID INNER JOIN
    FACULTY ON PERSONAL_DATA.FACULTY_ID = FACULTY.FACULITY_ID AND SPECIALIZATION.FACULTY_ID = FACULTY.FACULITY_ID
GROUP BY
    "RECORD".GRADE,
    STUDENT.STUDENT_ID,
    STUDENT.PESEL,
    STUDENT.ADMISSION_DATE,
    STUDENT.YEAR,
    STUDENT.SEMESTER,
    PERSONAL_DATA.FIRST_NAME,
    PERSONAL_DATA.LAST_NAME,
    PERSONAL_DATA.EMAIL,
    SPECIALIZATION.NAME,
    FACULTY.NAME;
--------------------------------------------------------
--  DDL for View STUDENT_GRADES_VIEW
--------------------------------------------------------

CREATE OR REPLACE NONEDITIONABLE VIEW "STUDENT_GRADES_VIEW" ("STUDENT_ID", "SUBJECT_NAME", "FORM", "GRADE", "PROFESSOR") AS
select
    rec.student_id,
    sbj.subject_name,
    grp."FORM",
    rec.grade,
    pd.first_name || ' ' || pd.last_name as PROFESSOR
from
    "RECORD" rec join
    "GROUP" grp on grp."GROUP_ID" = rec."GROUP_ID" join
    subject sbj on grp.subject_id = sbj.subject_id join
    personal_data pd on grp.professor_id = pd.user_id;
--------------------------------------------------------
--  DDL for View RECORD_VIEW
--------------------------------------------------------

CREATE OR REPLACE NONEDITIONABLE VIEW "RECORD_VIEW" ("STUDENT_ID", "PROFESSOR", "SUBJECT_NAME", "PARITY", "TIME", "FORM", "DAY", "STUDENT_LIMIT", "GRADE") AS
SELECT
    "RECORD".STUDENT_ID,
    PROFESSOR.DEGREE || ' ' ||
    PERSONAL_DATA.FIRST_NAME || ' ' ||
    PERSONAL_DATA.LAST_NAME as PROFESSOR,
    SUBJECT.SUBJECT_NAME,
    "GROUP".PARITY,
    "GROUP".TIME,
    "GROUP".FORM,
    "GROUP".DAY,
    "GROUP".STUDENT_LIMIT,
    "RECORD".GRADE
FROM
    "GROUP" INNER JOIN
    "RECORD" ON "RECORD"."GROUP_ID" = "GROUP"."GROUP_ID" INNER JOIN
    SUBJECT ON SUBJECT.SUBJECT_ID = "GROUP".SUBJECT_ID INNER JOIN
    PROFESSOR ON "GROUP".PROFESSOR_ID = PROFESSOR.PROFESSOR_ID INNER JOIN
    PERSONAL_DATA ON PROFESSOR.PROFESSOR_ID = PERSONAL_DATA.USER_ID;